spring:
  application:
    name: Integration_Protected_API  # Common application name

  server:
    port: 8080  # default port, can be overridden by profiles

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG  # Default logging level
