api:
  stock-news:
    query-params:
      key: symbol
      language: en
    url: https://real-time-finance-data.p.rapidapi.com/stock-news
  company-cashflow:
    query-params:
      key: symbol
      language: en
    url: https://real-time-finance-data.p.rapidapi.com/company-cash-flow
  currency-news:
    query-params:
      from: from_symbol
      to: to_symbol
      language: en
    url: https://real-time-finance-data.p.rapidapi.com/currency-news
  headers:
    X-RapidAPI-Key: 062c40283bmshf542cb9122404e1p1a18e2jsn19c9052df889
    X-RapidAPI-Host: real-time-finance-data.p.rapidapi.com